import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { validateIdentifier, IDENTIFIER_RE } from "../tools.js";

// ---------------------------------------------------------------------------
// validateIdentifier
// ---------------------------------------------------------------------------
describe("validateIdentifier", () => {
  it("accepts simple alphabetic names", () => {
    expect(() => validateIdentifier("Person", "label")).not.toThrow();
    expect(() => validateIdentifier("OWNS", "relationship type")).not.toThrow();
  });

  it("accepts names with underscores and digits", () => {
    expect(() => validateIdentifier("my_Label_2", "label")).not.toThrow();
    expect(() => validateIdentifier("_private", "label")).not.toThrow();
  });

  it("rejects names that start with a digit", () => {
    expect(() => validateIdentifier("1Person", "label")).toThrow(
      /Invalid label/
    );
  });

  it("rejects names containing spaces", () => {
    expect(() => validateIdentifier("my label", "label")).toThrow(
      /Invalid label/
    );
  });

  it("rejects names containing hyphens", () => {
    expect(() => validateIdentifier("my-label", "label")).toThrow(
      /Invalid label/
    );
  });

  it("rejects names with special characters", () => {
    expect(() => validateIdentifier("Label; DROP", "label")).toThrow(
      /Invalid label/
    );
  });

  it("rejects empty string", () => {
    expect(() => validateIdentifier("", "label")).toThrow(/Invalid label/);
  });
});

// ---------------------------------------------------------------------------
// IDENTIFIER_RE
// ---------------------------------------------------------------------------
describe("IDENTIFIER_RE", () => {
  it.each(["Person", "OWNS", "_private", "my_Var2", "A"])(
    "matches valid identifier: %s",
    (id) => {
      expect(IDENTIFIER_RE.test(id)).toBe(true);
    }
  );

  it.each(["1bad", "bad-name", "has space", "", "semi;colon", "dot.name"])(
    "rejects invalid identifier: %s",
    (id) => {
      expect(IDENTIFIER_RE.test(id)).toBe(false);
    }
  );
});

// ---------------------------------------------------------------------------
// runCypher tool — guarded by ENABLE_RUN_CYPHER env var
// ---------------------------------------------------------------------------
function runCypherGuard(): void {
  if (process.env.ENABLE_RUN_CYPHER !== "true") {
    throw new Error(
      "runCypher is disabled. Set ENABLE_RUN_CYPHER=true to enable it."
    );
  }
}

describe("runCypher env-var guard", () => {
  const originalEnv = process.env.ENABLE_RUN_CYPHER;

  afterEach(() => {
    if (originalEnv === undefined) {
      delete process.env.ENABLE_RUN_CYPHER;
    } else {
      process.env.ENABLE_RUN_CYPHER = originalEnv;
    }
  });

  it("throws when ENABLE_RUN_CYPHER is not set", () => {
    delete process.env.ENABLE_RUN_CYPHER;
    expect(runCypherGuard).toThrow(/runCypher is disabled/);
  });

  it("throws when ENABLE_RUN_CYPHER=false", () => {
    process.env.ENABLE_RUN_CYPHER = "false";
    expect(runCypherGuard).toThrow(/runCypher is disabled/);
  });

  it("does not throw when ENABLE_RUN_CYPHER=true", () => {
    process.env.ENABLE_RUN_CYPHER = "true";
    expect(runCypherGuard).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Cypher templates generated by tool handlers
// ---------------------------------------------------------------------------
describe("upsertEntity Cypher template", () => {
  it("uses MERGE with id parameter", () => {
    const label = "Person";
    const cypher = `MERGE (n:${label} { id: $id }) SET n += $properties RETURN n`;
    expect(cypher).toBe(
      "MERGE (n:Person { id: $id }) SET n += $properties RETURN n"
    );
    expect(cypher).toContain("$id");
    expect(cypher).toContain("$properties");
  });
});

describe("upsertRelation Cypher template", () => {
  it("builds the expected multi-line merge query", () => {
    const fromLabel = "Person";
    const toLabel = "Repo";
    const relType = "OWNS";
    const cypher = [
      `MERGE (a:${fromLabel} { id: $fromId })`,
      `MERGE (b:${toLabel} { id: $toId })`,
      `MERGE (a)-[r:${relType}]->(b)`,
      `SET r += $properties`,
      `RETURN a, r, b`,
    ].join(" ");
    expect(cypher).toContain("$fromId");
    expect(cypher).toContain("$toId");
    expect(cypher).toContain("$properties");
    expect(cypher).toContain("MERGE (a)-[r:OWNS]->(b)");
  });
});

// ---------------------------------------------------------------------------
// neo4j module — getDriver / closeDriver
// ---------------------------------------------------------------------------
describe("neo4j module", () => {
  beforeEach(() => {
    vi.resetModules();
  });

  it("getDriver returns the same instance on repeated calls", async () => {
    const mockDriver = {
      verifyConnectivity: vi.fn().mockResolvedValue(undefined),
      session: vi.fn(),
      close: vi.fn().mockResolvedValue(undefined),
    };
    vi.doMock("neo4j-driver", () => ({
      default: {
        driver: vi.fn().mockReturnValue(mockDriver),
        auth: { basic: vi.fn().mockReturnValue({}) },
      },
    }));
    const { getDriver } = await import("../neo4j.js");
    const d1 = getDriver();
    const d2 = getDriver();
    expect(d1).toBe(d2);
  });

  it("closeDriver sets driver to null so next getDriver creates a new one", async () => {
    const mockDriver = {
      verifyConnectivity: vi.fn().mockResolvedValue(undefined),
      session: vi.fn(),
      close: vi.fn().mockResolvedValue(undefined),
    };
    const driverFn = vi.fn().mockReturnValue(mockDriver);
    vi.doMock("neo4j-driver", () => ({
      default: { driver: driverFn, auth: { basic: vi.fn().mockReturnValue({}) } },
    }));
    const { getDriver, closeDriver } = await import("../neo4j.js");
    getDriver();
    await closeDriver();
    getDriver();
    // driver factory called twice — once before close, once after
    expect(driverFn).toHaveBeenCalledTimes(2);
  });
});
